{% set name = "gsl-lite" %}
{% set version = "0.34.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/martinmoene/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: a7d5b2672b78704ca03df9ef65bc274d8f8cacad3ca950365eef9e25b50324c5
  patches:
    - 0001-Use-gsl-lite-as-CMake-package-folder-name-146-thanks.patch

build:
  number: 0

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - make  # [unix]

test:
  requires:
    - cmake
    - {{ compiler('cxx') }}
    - make  # [unix]
    - ninja
  files:
    - test

  commands:
    - echo on  # [win]
    - cd test

    - mkdir build_default
    - cd build_default
    - cmake .. -G"%CMAKE_GENERATOR%" -DCMAKE_BUILD_TYPE=Release  # [win]
    - cmake .. -G"$CMAKE_GENERATOR" -DCMAKE_BUILD_TYPE=Release  # [unix]
    - cmake --build . --config Release
    - ./program  # [unix]
    - Release\\program.exe  # [win]
    - cd ..

    - mkdir build_ninja
    - cd build_ninja
    - cmake .. -G"Ninja" -DCMAKE_BUILD_TYPE=Release
    - cmake --build . --config Release
    - ./program  # [unix]
    - program.exe  # [win]

about:
  home: https://github.com/martinmoene/gsl-lite
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A single-file header-only version of ISO C++ Guidelines Support Library (GSL) for C++98, C++11 and later'

extra:
  recipe-maintainers:
    - tadeu
