{% set name = "gsl-lite" %}
{% set version = "0.32.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/martinmoene/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 134c891b0b0f038d622554faa4040f6d419c534ed18c1b893f4f3ff788515d10

build:
  number: 1

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - make  # [unix]

test:
  requires:
    - cmake
    - {{ compiler('cxx') }}
    - make  # [unix]
    - ninja
  files:
    - test

  commands:
    - echo on  # [win]
    - cd test

    - mkdir build_default
    - cd build_default
    - cmake .. -G"%CMAKE_GENERATOR%" -DCMAKE_BUILD_TYPE=Release  # [win]
    - cmake .. -G"$CMAKE_GENERATOR" -DCMAKE_BUILD_TYPE=Release  # [unix]
    - cmake --build . --config Release
    - ./program  # [unix]
    - Release\\program.exe  # [win]
    - cd ..

    - mkdir build_ninja
    - cd build_ninja
    - cmake .. -G"Ninja" -DCMAKE_BUILD_TYPE=Release
    - cmake --build . --config Release
    - ./program  # [unix]
    - program.exe  # [win]

about:
  home: https://github.com/martinmoene/gsl-lite
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A single-file header-only version of ISO C++ Guidelines Support Library (GSL) for C++98, C++11 and later'

extra:
  recipe-maintainers:
    - tadeu
