travis:
  secure:
    BINSTAR_TOKEN: t0NOU361INKUClQARiAx5hZgUoG6rXZagMAwUud8Ji7Koao9572Jt07bsSKFIBLJ1zI0KoHmRBzJo49q6diyOHImEmuMjHS1WNkBZmBFoMeYUoxV0UFtLIDaiJqBySb+nlPBLO4iqcirZwP5dfkEvubaWurvvIrdnqkuiNt3uzIeUkM9XBIoLlQ2oQ2qZZ8pI6Sv6ZWvnhz32drKj+2YImZ60hhQhb7hLQ8M+LCFq6fh6Jup8YaSyMoLiDzAQ8G6Q6lFiLxdMuPoojo7VNOvm2tMactwsvkl+WPIBU+c/8x0ohdLQwgI5vetOC4J+zB2LHDzv7cbJ7EuUDJAx0hfyaAh3pk2Z2a/4MbfRVI8ehkt0ofar9H8FFWNjAksrjzRCioDL7nQyIsrIiS0/TA2Pq8QxqOY3h6WiIJvzGVPu9oiNY1y1HdWhgwAnqVXOvBN7Sopppo3wpUb68AN2Wsfg9v5UBE2pu+aYg2WZhq0/jAGVpKLNsjw0Uegj9dDY2tlgitikdX3CQjdVrBA+sQOFBqeXj6aaAAgrKD47fv7BCwDwtX4alRgtDuQqbtbx//OzxAnaRurdnQQbPIN8MGG5o4S2QdwSIlqR6nN/F39PJ9FRdrO9iNz9R26d8sVTvPaH9iShk9Gcrut43o939adCoSMF4EbgH61BNbn6No7Otc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
