travis:
  secure:
    BINSTAR_TOKEN: dzmpWv9EL5N/2kv6lWW82Y3gTZ9wWLLP5LmfIZ+2cExLOzsjA+xPst53eVHorT/StTncg+cDYSCa7frLb2w2Pu/8D/uqlw7fYISR/Jcshdoqr62dUINzCD8SM0dljOJ5FeQ+xJtswbS7Jj9B5nq25EqljmH2VokFygZ60RU79SwBXFRCBydsmHwJYODsLiz1Svnavp2ajmpqBqMlsSCfT/Uf+3ZfSu54KnU/HWJPue6k45H/ZHC6aafRFiRYuI9fVKg61tw2ektKr07rSidUgIBnM2VnxDo0RftFVjn4LhLE9g+P++iHZ2TwaJv1GrV/wLdXEP9pMEo40+x6F+1iK7Q9G7m2fwVhi7H1fcX5QZNLg0lPHz0OlAoXjc4oCSNdf/1bVuvxrOE+1SYAUu3vGnAroWH5LdNoQSBmNZaOHK2tTeU3u4BzGj7X43fjfWnPybakE8MXN7+zhrX8hE7amoKXZ3oumgGoP7Yc6uw35LiepKOEwbw6HrsoPjP20zvjyfk6EOsQf8mrmPJN3gEtt1lEiEn9XEy9WCnQ/NaIf89KdL7FBCShd+lBe0MvGKikV8yv8U0lfpTeHiqaucFVMnKeZfyTC6Qg8h4VZNqFcSxowC8HUXuXEVKC9QA/Xt/A21QV8hFDW8CqHYzxt5a07bCvx7ztRNYOdejd3pCebo8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
